[workspace]
name = "oxrsys-windows"
channels = ["conda-forge"]
platforms = ["win-64"]

[dependencies]
cmake = ">=3.28"
ninja = "*"
qt6-main = "*"
libvulkan-headers = ">=1.4.357.0,<2"
libvulkan-loader = ">=1.4.357.0,<2"
