# SPDX-License-Identifier: Apache-2.0 OR MIT
cmake_minimum_required(VERSION 3.24)
# Fails when the test binary lists a non-control case that EXPECTED does not name.
execute_process(COMMAND ${TESTS} --list OUTPUT_VARIABLE listed RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "${TESTS} --list exited ${rc}")
endif()
string(REPLACE "\n" ";" listed "${listed}")
set(missing "")
foreach(name IN LISTS listed)
  if(name STREQUAL "" OR name MATCHES "^control[.]")
    continue()
  endif()
  if(NOT name IN_LIST EXPECTED)
    list(APPEND missing ${name})
  endif()
endforeach()
if(missing)
  message(FATAL_ERROR "cases not registered with ctest: ${missing}")
endif()
