#!/usr/bin/env python3
"""Write a SPIR-V module as a C++ uint32_t array: embed_spv.py <in.spv> <out.h> <kernel>"""
import struct
import sys

data = open(sys.argv[1], "rb").read()
words = struct.unpack(f"<{len(data) // 4}I", data)
rows = [", ".join(f"0x{w:08x}u" for w in words[i:i + 8]) for i in range(0, len(words), 8)]
with open(sys.argv[2], "w", newline="\n") as out:
    out.write(f"// Generated by kernels/simulator/gen.sh from slang/{sys.argv[3]}.slang.\n")
    out.write("#pragma once\n#include <cstdint>\n")
    out.write(f"static const uint32_t k_{sys.argv[3]}_spv[] = {{\n" + ",\n".join(rows) + "\n};\n")
