// SPDX-License-Identifier: MPL-2.0
// Generated by driver/abi/vtbl.py from openvr_driver.vtbl; do not edit.

#pragma once

#include "openvr_driver_types.h"

namespace oxrvr
{

class IServerTrackedDeviceProvider;
class ITrackedDeviceServerDriver;
class IVRDisplayComponent;
class IVRDriverDirectModeComponent;
class IVRDriverContext;
class IVRServerDriverHost;
class IVRProperties;
class IVRDriverLog;
class IVRSettings;
class IVRDriverInput;

class IServerTrackedDeviceProvider
{
public:
    virtual EVRInitError Init(IVRDriverContext *pDriverContext) = 0;
    virtual void Cleanup() = 0;
    virtual const char *const * GetInterfaceVersions() = 0;
    virtual void RunFrame() = 0;
    virtual bool ShouldBlockStandbyMode() = 0;
    virtual void EnterStandby() = 0;
    virtual void LeaveStandby() = 0;
};
inline constexpr char kIServerTrackedDeviceProvider_Version[] = "IServerTrackedDeviceProvider_004";
inline constexpr uint32_t kIServerTrackedDeviceProvider_SlotCount = 7;

class ITrackedDeviceServerDriver
{
public:
    virtual EVRInitError Activate(uint32_t unObjectId) = 0;
    virtual void Deactivate() = 0;
    virtual void EnterStandby() = 0;
    virtual void * GetComponent(const char *pchComponentNameAndVersion) = 0;
    virtual void DebugRequest(const char *pchRequest, char *pchResponseBuffer, uint32_t unResponseBufferSize) = 0;
    virtual DriverPose_t GetPose() = 0;
};
inline constexpr char kITrackedDeviceServerDriver_Version[] = "ITrackedDeviceServerDriver_005";
inline constexpr uint32_t kITrackedDeviceServerDriver_SlotCount = 6;

class IVRDisplayComponent
{
public:
    virtual void GetWindowBounds(int32_t *pnX, int32_t *pnY, uint32_t *pnWidth, uint32_t *pnHeight) = 0;
    virtual bool IsDisplayOnDesktop() = 0;
    virtual bool IsDisplayRealDisplay() = 0;
    virtual void GetRecommendedRenderTargetSize(uint32_t *pnWidth, uint32_t *pnHeight) = 0;
    virtual void GetEyeOutputViewport(EVREye eEye, uint32_t *pnX, uint32_t *pnY, uint32_t *pnWidth, uint32_t *pnHeight) = 0;
    virtual void GetProjectionRaw(EVREye eEye, float *pfLeft, float *pfRight, float *pfTop, float *pfBottom) = 0;
    virtual DistortionCoordinates_t ComputeDistortion(EVREye eEye, float fU, float fV) = 0;
    virtual bool ComputeInverseDistortion(HmdVector2_t *pResult, EVREye eEye, uint32_t unChannel, float fU, float fV) = 0;
};
inline constexpr char kIVRDisplayComponent_Version[] = "IVRDisplayComponent_003";
inline constexpr uint32_t kIVRDisplayComponent_SlotCount = 8;

class IVRDriverDirectModeComponent
{
public:
    virtual void CreateSwapTextureSet(uint32_t unPid, const SwapTextureSetDesc_t *pSwapTextureSetDesc, SwapTextureSet_t *pOutSwapTextureSet) = 0;
    virtual void DestroySwapTextureSet(SharedTextureHandle_t sharedTextureHandle) = 0;
    virtual void DestroyAllSwapTextureSets(uint32_t unPid) = 0;
    virtual void GetNextSwapTextureSetIndex(SharedTextureHandle_t *sharedTextureHandles, uint32_t (*pIndices)[2]) = 0;
    virtual void SubmitLayer(const SubmitLayerPerEye_t (&perEye)[2]) = 0;
    virtual void Present(SharedTextureHandle_t syncTexture) = 0;
    virtual void PostPresent(const Throttling_t *pThrottling) = 0;
    virtual void GetFrameTiming(DriverDirectMode_FrameTiming *pFrameTiming) = 0;
};
inline constexpr char kIVRDriverDirectModeComponent_Version[] = "IVRDriverDirectModeComponent_009";
inline constexpr uint32_t kIVRDriverDirectModeComponent_SlotCount = 8;

class IVRDriverContext
{
public:
    virtual void * GetGenericInterface(const char *pchInterfaceVersion, EVRInitError *peError) = 0;
    virtual DriverHandle_t GetDriverHandle() = 0;
};
inline constexpr char kIVRDriverContext_Version[] = "";
inline constexpr uint32_t kIVRDriverContext_SlotCount = 2;

class IVRServerDriverHost
{
public:
    virtual bool TrackedDeviceAdded(const char *pchDeviceSerialNumber, ETrackedDeviceClass eDeviceClass, ITrackedDeviceServerDriver *pDriver) = 0;
    virtual void TrackedDevicePoseUpdated(uint32_t unWhichDevice, const DriverPose_t &newPose, uint32_t unPoseStructSize) = 0;
    virtual void VsyncEvent(double vsyncTimeOffsetSeconds) = 0;
    virtual void Pad3_VendorSpecificEvent() = 0;
    virtual bool IsExiting() = 0;
    virtual bool PollNextEvent(VREvent_t *pEvent, uint32_t uncbVREvent) = 0;
};
inline constexpr char kIVRServerDriverHost_Version[] = "IVRServerDriverHost_006";
inline constexpr uint32_t kIVRServerDriverHost_SlotCount = 6;

class IVRProperties
{
public:
    virtual void Pad0_ReadPropertyBatch() = 0;
    virtual ETrackedPropertyError WritePropertyBatch(PropertyContainerHandle_t ulContainerHandle, PropertyWrite_t *pBatch, uint32_t unBatchEntryCount) = 0;
    virtual void Pad2_GetPropErrorNameFromEnum() = 0;
    virtual PropertyContainerHandle_t TrackedDeviceToPropertyContainer(TrackedDeviceIndex_t nDevice) = 0;
};
inline constexpr char kIVRProperties_Version[] = "IVRProperties_001";
inline constexpr uint32_t kIVRProperties_SlotCount = 4;

class IVRDriverLog
{
public:
    virtual void Log(const char *pchLogMessage) = 0;
};
inline constexpr char kIVRDriverLog_Version[] = "IVRDriverLog_001";
inline constexpr uint32_t kIVRDriverLog_SlotCount = 1;

class IVRSettings
{
public:
    virtual void Pad0_GetSettingsErrorNameFromEnum() = 0;
    virtual void Pad1_SetBool() = 0;
    virtual void Pad2_SetInt32() = 0;
    virtual void Pad3_SetFloat() = 0;
    virtual void Pad4_SetString() = 0;
    virtual void Pad5_GetBool() = 0;
    virtual int32_t GetInt32(const char *pchSection, const char *pchSettingsKey, EVRSettingsError *peError) = 0;
    virtual void Pad7_GetFloat() = 0;
    virtual void GetString(const char *pchSection, const char *pchSettingsKey, char *pchValue, uint32_t unValueLen, EVRSettingsError *peError) = 0;
};
inline constexpr char kIVRSettings_Version[] = "IVRSettings_003";
inline constexpr uint32_t kIVRSettings_SlotCount = 9;

class IVRDriverInput
{
public:
    virtual EVRInputError CreateBooleanComponent(PropertyContainerHandle_t ulContainer, const char *pchName, VRInputComponentHandle_t *pHandle) = 0;
    virtual EVRInputError UpdateBooleanComponent(VRInputComponentHandle_t ulComponent, bool bNewValue, double fTimeOffset) = 0;
    virtual EVRInputError CreateScalarComponent(PropertyContainerHandle_t ulContainer, const char *pchName, VRInputComponentHandle_t *pHandle, EVRScalarType eType, EVRScalarUnits eUnits) = 0;
    virtual EVRInputError UpdateScalarComponent(VRInputComponentHandle_t ulComponent, float fNewValue, double fTimeOffset) = 0;
};
inline constexpr char kIVRDriverInput_Version[] = "IVRDriverInput_004";
inline constexpr uint32_t kIVRDriverInput_SlotCount = 4;

struct SlotProbe
{
    const char *interfaceName;
    const char *methodName;
    uint32_t slot;
    void (*call)(void *object);
};

inline const SlotProbe kSlotProbes[] = {
    {"IServerTrackedDeviceProvider", "Init", 0, [](void *o) { static_cast<IServerTrackedDeviceProvider *>(o)->Init({}); }},
    {"IServerTrackedDeviceProvider", "Cleanup", 1, [](void *o) { static_cast<IServerTrackedDeviceProvider *>(o)->Cleanup(); }},
    {"IServerTrackedDeviceProvider", "GetInterfaceVersions", 2, [](void *o) { static_cast<IServerTrackedDeviceProvider *>(o)->GetInterfaceVersions(); }},
    {"IServerTrackedDeviceProvider", "RunFrame", 3, [](void *o) { static_cast<IServerTrackedDeviceProvider *>(o)->RunFrame(); }},
    {"IServerTrackedDeviceProvider", "ShouldBlockStandbyMode", 4, [](void *o) { static_cast<IServerTrackedDeviceProvider *>(o)->ShouldBlockStandbyMode(); }},
    {"IServerTrackedDeviceProvider", "EnterStandby", 5, [](void *o) { static_cast<IServerTrackedDeviceProvider *>(o)->EnterStandby(); }},
    {"IServerTrackedDeviceProvider", "LeaveStandby", 6, [](void *o) { static_cast<IServerTrackedDeviceProvider *>(o)->LeaveStandby(); }},
    {"ITrackedDeviceServerDriver", "Activate", 0, [](void *o) { static_cast<ITrackedDeviceServerDriver *>(o)->Activate({}); }},
    {"ITrackedDeviceServerDriver", "Deactivate", 1, [](void *o) { static_cast<ITrackedDeviceServerDriver *>(o)->Deactivate(); }},
    {"ITrackedDeviceServerDriver", "EnterStandby", 2, [](void *o) { static_cast<ITrackedDeviceServerDriver *>(o)->EnterStandby(); }},
    {"ITrackedDeviceServerDriver", "GetComponent", 3, [](void *o) { static_cast<ITrackedDeviceServerDriver *>(o)->GetComponent({}); }},
    {"ITrackedDeviceServerDriver", "DebugRequest", 4, [](void *o) { static_cast<ITrackedDeviceServerDriver *>(o)->DebugRequest({}, {}, {}); }},
    {"ITrackedDeviceServerDriver", "GetPose", 5, [](void *o) { static_cast<ITrackedDeviceServerDriver *>(o)->GetPose(); }},
    {"IVRDisplayComponent", "GetWindowBounds", 0, [](void *o) { static_cast<IVRDisplayComponent *>(o)->GetWindowBounds({}, {}, {}, {}); }},
    {"IVRDisplayComponent", "IsDisplayOnDesktop", 1, [](void *o) { static_cast<IVRDisplayComponent *>(o)->IsDisplayOnDesktop(); }},
    {"IVRDisplayComponent", "IsDisplayRealDisplay", 2, [](void *o) { static_cast<IVRDisplayComponent *>(o)->IsDisplayRealDisplay(); }},
    {"IVRDisplayComponent", "GetRecommendedRenderTargetSize", 3, [](void *o) { static_cast<IVRDisplayComponent *>(o)->GetRecommendedRenderTargetSize({}, {}); }},
    {"IVRDisplayComponent", "GetEyeOutputViewport", 4, [](void *o) { static_cast<IVRDisplayComponent *>(o)->GetEyeOutputViewport({}, {}, {}, {}, {}); }},
    {"IVRDisplayComponent", "GetProjectionRaw", 5, [](void *o) { static_cast<IVRDisplayComponent *>(o)->GetProjectionRaw({}, {}, {}, {}, {}); }},
    {"IVRDisplayComponent", "ComputeDistortion", 6, [](void *o) { static_cast<IVRDisplayComponent *>(o)->ComputeDistortion({}, {}, {}); }},
    {"IVRDisplayComponent", "ComputeInverseDistortion", 7, [](void *o) { static_cast<IVRDisplayComponent *>(o)->ComputeInverseDistortion({}, {}, {}, {}, {}); }},
    {"IVRDriverDirectModeComponent", "CreateSwapTextureSet", 0, [](void *o) { static_cast<IVRDriverDirectModeComponent *>(o)->CreateSwapTextureSet({}, {}, {}); }},
    {"IVRDriverDirectModeComponent", "DestroySwapTextureSet", 1, [](void *o) { static_cast<IVRDriverDirectModeComponent *>(o)->DestroySwapTextureSet({}); }},
    {"IVRDriverDirectModeComponent", "DestroyAllSwapTextureSets", 2, [](void *o) { static_cast<IVRDriverDirectModeComponent *>(o)->DestroyAllSwapTextureSets({}); }},
    {"IVRDriverDirectModeComponent", "GetNextSwapTextureSetIndex", 3, [](void *o) { static_cast<IVRDriverDirectModeComponent *>(o)->GetNextSwapTextureSetIndex({}, {}); }},
    {"IVRDriverDirectModeComponent", "SubmitLayer", 4, [](void *o) { static_cast<IVRDriverDirectModeComponent *>(o)->SubmitLayer({}); }},
    {"IVRDriverDirectModeComponent", "Present", 5, [](void *o) { static_cast<IVRDriverDirectModeComponent *>(o)->Present({}); }},
    {"IVRDriverDirectModeComponent", "PostPresent", 6, [](void *o) { static_cast<IVRDriverDirectModeComponent *>(o)->PostPresent({}); }},
    {"IVRDriverDirectModeComponent", "GetFrameTiming", 7, [](void *o) { static_cast<IVRDriverDirectModeComponent *>(o)->GetFrameTiming({}); }},
    {"IVRDriverContext", "GetGenericInterface", 0, [](void *o) { static_cast<IVRDriverContext *>(o)->GetGenericInterface({}, {}); }},
    {"IVRDriverContext", "GetDriverHandle", 1, [](void *o) { static_cast<IVRDriverContext *>(o)->GetDriverHandle(); }},
    {"IVRServerDriverHost", "TrackedDeviceAdded", 0, [](void *o) { static_cast<IVRServerDriverHost *>(o)->TrackedDeviceAdded({}, {}, {}); }},
    {"IVRServerDriverHost", "TrackedDevicePoseUpdated", 1, [](void *o) { static_cast<IVRServerDriverHost *>(o)->TrackedDevicePoseUpdated({}, {}, {}); }},
    {"IVRServerDriverHost", "VsyncEvent", 2, [](void *o) { static_cast<IVRServerDriverHost *>(o)->VsyncEvent({}); }},
    {"IVRServerDriverHost", "Pad3_VendorSpecificEvent", 3, [](void *o) { static_cast<IVRServerDriverHost *>(o)->Pad3_VendorSpecificEvent(); }},
    {"IVRServerDriverHost", "IsExiting", 4, [](void *o) { static_cast<IVRServerDriverHost *>(o)->IsExiting(); }},
    {"IVRServerDriverHost", "PollNextEvent", 5, [](void *o) { static_cast<IVRServerDriverHost *>(o)->PollNextEvent({}, {}); }},
    {"IVRProperties", "Pad0_ReadPropertyBatch", 0, [](void *o) { static_cast<IVRProperties *>(o)->Pad0_ReadPropertyBatch(); }},
    {"IVRProperties", "WritePropertyBatch", 1, [](void *o) { static_cast<IVRProperties *>(o)->WritePropertyBatch({}, {}, {}); }},
    {"IVRProperties", "Pad2_GetPropErrorNameFromEnum", 2, [](void *o) { static_cast<IVRProperties *>(o)->Pad2_GetPropErrorNameFromEnum(); }},
    {"IVRProperties", "TrackedDeviceToPropertyContainer", 3, [](void *o) { static_cast<IVRProperties *>(o)->TrackedDeviceToPropertyContainer({}); }},
    {"IVRDriverLog", "Log", 0, [](void *o) { static_cast<IVRDriverLog *>(o)->Log({}); }},
    {"IVRSettings", "Pad0_GetSettingsErrorNameFromEnum", 0, [](void *o) { static_cast<IVRSettings *>(o)->Pad0_GetSettingsErrorNameFromEnum(); }},
    {"IVRSettings", "Pad1_SetBool", 1, [](void *o) { static_cast<IVRSettings *>(o)->Pad1_SetBool(); }},
    {"IVRSettings", "Pad2_SetInt32", 2, [](void *o) { static_cast<IVRSettings *>(o)->Pad2_SetInt32(); }},
    {"IVRSettings", "Pad3_SetFloat", 3, [](void *o) { static_cast<IVRSettings *>(o)->Pad3_SetFloat(); }},
    {"IVRSettings", "Pad4_SetString", 4, [](void *o) { static_cast<IVRSettings *>(o)->Pad4_SetString(); }},
    {"IVRSettings", "Pad5_GetBool", 5, [](void *o) { static_cast<IVRSettings *>(o)->Pad5_GetBool(); }},
    {"IVRSettings", "GetInt32", 6, [](void *o) { static_cast<IVRSettings *>(o)->GetInt32({}, {}, {}); }},
    {"IVRSettings", "Pad7_GetFloat", 7, [](void *o) { static_cast<IVRSettings *>(o)->Pad7_GetFloat(); }},
    {"IVRSettings", "GetString", 8, [](void *o) { static_cast<IVRSettings *>(o)->GetString({}, {}, {}, {}, {}); }},
    {"IVRDriverInput", "CreateBooleanComponent", 0, [](void *o) { static_cast<IVRDriverInput *>(o)->CreateBooleanComponent({}, {}, {}); }},
    {"IVRDriverInput", "UpdateBooleanComponent", 1, [](void *o) { static_cast<IVRDriverInput *>(o)->UpdateBooleanComponent({}, {}, {}); }},
    {"IVRDriverInput", "CreateScalarComponent", 2, [](void *o) { static_cast<IVRDriverInput *>(o)->CreateScalarComponent({}, {}, {}, {}, {}); }},
    {"IVRDriverInput", "UpdateScalarComponent", 3, [](void *o) { static_cast<IVRDriverInput *>(o)->UpdateScalarComponent({}, {}, {}); }},
};

} // namespace oxrvr
