# SPDX-License-Identifier: MPL-2.0
"""Generate and check the driver interface header from openvr_driver.vtbl.

  vtbl.py generate <vtbl> <out.h>     write the header
  vtbl.py fresh <vtbl> <out.h>        fail when the committed header differs from a regeneration
  vtbl.py swapped <vtbl> <out.h>      write the header with the first two slot lines exchanged,
                                      the slot probe's negative control
  vtbl.py refdiff <vtbl> <sdk.h>      fail when a slot name or version differs from the SDK header
  vtbl.py self-test                   negative controls for the parser and the reference diff
"""

import re
import sys

LINE_RE = re.compile(r'^(\d+):\s*(.*)$')
HEAD_RE = re.compile(r'^interface\s+(\w+)\s+"([^"]*)"\s+(implement|call)$')
SIG_RE = re.compile(r'^(.+?[\s\*&])(\w+)\s*\((.*)\)\s*;$')
PAD_RE = re.compile(r'^pad\s+(\w+)$')


class Interface:
    def __init__(self, name, version, role):
        self.name, self.version, self.role = name, version, role
        self.slots = []  # (slot, name, return, params or None for pad)


def parse(text):
    interfaces = []
    current = None
    for number, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith('#'):
            continue
        head = HEAD_RE.match(line)
        if head:
            current = Interface(*head.groups())
            interfaces.append(current)
            continue
        slot = LINE_RE.match(line)
        if not slot or current is None:
            raise SystemExit(f'line {number}: not a slot or interface line: {raw}')
        index, body = int(slot.group(1)), slot.group(2).strip()
        pad = PAD_RE.match(body)
        if pad:
            if current.role == 'implement':
                raise SystemExit(f'line {number}: {current.name} is implemented, so it cannot pad')
            current.slots.append((index, pad.group(1), None, None))
            continue
        sig = SIG_RE.match(body)
        if not sig:
            raise SystemExit(f'line {number}: unparsed signature: {body}')
        params = sig.group(3).strip()
        current.slots.append((index, sig.group(2), sig.group(1).strip(), '' if params == 'void' else params))
    for interface in interfaces:
        numbers = sorted(s[0] for s in interface.slots)
        if numbers != list(range(len(numbers))):
            raise SystemExit(f'{interface.name}: slots {numbers} are not 0..{len(numbers) - 1}')
    return interfaces


def param_count(params):
    if not params:
        return 0
    depth, count = 0, 1
    for ch in params:
        depth += ch in '(['
        depth -= ch in ')]'
        count += ch == ',' and depth == 0
    return count


def generate(interfaces):
    out = [
        '// SPDX-License-Identifier: MPL-2.0',
        '// Generated by driver/abi/vtbl.py from openvr_driver.vtbl; do not edit.',
        '',
        '#pragma once',
        '',
        '#include "openvr_driver_types.h"',
        '',
        'namespace oxrvr',
        '{',
        '',
    ]
    for interface in interfaces:
        out.append(f'class {interface.name};')
    out.append('')
    for interface in interfaces:
        out.append(f'class {interface.name}')
        out.append('{')
        out.append('public:')
        # Emitted in file order, so a line out of slot order shows up in the slot probe.
        for index, name, ret, params in interface.slots:
            if params is None:
                out.append(f'    virtual void Pad{index}_{name}() = 0;')
            else:
                out.append(f'    virtual {ret} {name}({params}) = 0;')
        out.append('};')
        out.append(f'inline constexpr char k{interface.name}_Version[] = "{interface.version}";')
        out.append(f'inline constexpr uint32_t k{interface.name}_SlotCount = {len(interface.slots)};')
        out.append('')
    out.append('struct SlotProbe')
    out.append('{')
    out.append('    const char *interfaceName;')
    out.append('    const char *methodName;')
    out.append('    uint32_t slot;')
    out.append('    void (*call)(void *object);')
    out.append('};')
    out.append('')
    out.append('inline const SlotProbe kSlotProbes[] = {')
    for interface in interfaces:
        for index, name, ret, params in interface.slots:
            method = f'Pad{index}_{name}' if params is None else name
            args = ', '.join(['{}'] * param_count(params))
            out.append(f'    {{"{interface.name}", "{method}", {index}, [](void *o) {{ '
                       f'static_cast<{interface.name} *>(o)->{method}({args}); }}}},')
    out.append('};')
    out.append('')
    out.append('} // namespace oxrvr')
    out.append('')
    return '\n'.join(out)


def strip_comments(text):
    text = re.sub(r'/\*.*?\*/', ' ', text, flags=re.S)
    return re.sub(r'//[^\n]*', ' ', text)


def reference_slots(header, name):
    text = strip_comments(header)
    match = re.search(r'\bclass\s+' + name + r'\s*\{', text)
    if not match:
        return None, None
    depth, i = 1, match.end()
    while depth and i < len(text):
        depth += text[i] == '{'
        depth -= text[i] == '}'
        i += 1
    body = text[match.end():i]
    # Default bodies `{ ... }` of non-pure virtuals hold no `virtual`, so splitting on it is safe.
    names = [re.search(r'(\w+)\s*\(', chunk).group(1) for chunk in body.split('virtual')[1:]]
    version = re.search(r'\b' + name + r'_Version\s*=\s*"([^"]+)"', text)
    return names, version.group(1) if version else ''


def refdiff(interfaces, header):
    problems = []
    for interface in interfaces:
        names, version = reference_slots(header, interface.name)
        if names is None:
            problems.append(f'{interface.name}: not in the reference header')
            continue
        if version != interface.version:
            problems.append(f'{interface.name}: version {interface.version!r}, reference {version!r}')
        for index, name, _, _ in sorted(interface.slots):
            reference = names[index] if index < len(names) else None
            if reference != name:
                problems.append(f'{interface.name} slot {index}: {name}, reference {reference}')
        if interface.role == 'implement' and len(interface.slots) != len(names):
            problems.append(f'{interface.name}: {len(interface.slots)} slots, reference {len(names)}')
    return problems


def self_test():
    vtbl = ('interface IA "IA_001" implement\n0: void One(void);\n1: int Two(int a, float (*b)[2]);\n'
            'interface IB "" call\n0: pad Skip\n1: void Used(const char *s);\n')
    header = ('class IA { public: virtual void One() = 0; /* virtual Fake() */ '
              'virtual int Two(int a, float (*b)[2]) { return 0; } };\n'
              'static const char *IA_Version = "IA_001";\n'
              'class IB { public: virtual void Skip() = 0; virtual void Used(const char *s) = 0; };\n')
    failures = 0

    def expect(label, condition):
        nonlocal failures
        print(('PASS ' if condition else 'FAIL ') + label)
        failures += not condition

    interfaces = parse(vtbl)
    expect('matching reference diffs clean', refdiff(interfaces, header) == [])
    expect('param count sees through (*b)[2]', param_count('int a, float (*b)[2]') == 2)
    swapped = header.replace('virtual void Skip() = 0; virtual void Used(const char *s) = 0;',
                             'virtual void Used(const char *s) = 0; virtual void Skip() = 0;')
    expect('reordered reference slot fails', refdiff(interfaces, swapped) != [])
    expect('reference version mismatch fails', refdiff(interfaces, header.replace('"IA_001"', '"IA_002"')) != [])
    expect('missing implemented slot fails',
           refdiff(interfaces, header.replace('virtual int Two', 'virtual int Two(int a) = 0; virtual int Three')) != [])
    for label, bad in [('pad in an implemented interface is refused', vtbl.replace('0: void One(void);', '0: pad One')),
                       ('slot gap is refused', vtbl.replace('1: int Two', '2: int Two'))]:
        try:
            parse(bad)
            expect(label, False)
        except SystemExit:
            expect(label, True)
    return failures


def main(argv):
    if len(argv) == 2 and argv[1] == 'self-test':
        return 1 if self_test() else 0
    if len(argv) != 4:
        print(__doc__)
        return 2
    command, vtbl_path, other = argv[1:]
    with open(vtbl_path, encoding='utf-8') as f:
        interfaces = parse(f.read())
    if command == 'generate':
        with open(other, 'w', encoding='utf-8', newline='\n') as f:
            f.write(generate(interfaces))
        return 0
    if command == 'swapped':
        first = interfaces[0].slots
        first[0], first[1] = first[1], first[0]
        with open(other, 'w', encoding='utf-8', newline='\n') as f:
            f.write(generate(interfaces))
        return 0
    if command == 'fresh':
        with open(other, encoding='utf-8') as f:
            same = f.read() == generate(interfaces)
        print('fresh' if same else f'{other} differs from a regeneration of {vtbl_path}')
        return 0 if same else 1
    if command == 'refdiff':
        with open(other, encoding='utf-8', errors='replace') as f:
            problems = refdiff(interfaces, f.read())
        slots = sum(len(i.slots) for i in interfaces)
        for problem in problems:
            print('FAIL ' + problem)
        print(f'{len(interfaces)} interfaces, {slots} slots, {len(problems)} differences')
        return 1 if problems else 0
    print(__doc__)
    return 2


if __name__ == '__main__':
    sys.exit(main(sys.argv))
