# SPDX-License-Identifier: MPL-2.0
#
# Builds the OXRSys controller from Godot CSG (Manifold) and writes it as a PC VR render model:
#   godot --headless --path driver/resources/rendermodels --script make_controller.gd
# Controller space: -Z forward along the laser, +Y up, origin at the tracked point, metres.
extends SceneTree

const OUT := "res://oxrsys_controller/"

var body: CSGCombiner3D
var frames := 0


func part(node: CSGShape3D, position: Vector3, rotation_deg := Vector3.ZERO, operation := CSGShape3D.OPERATION_UNION, scale := Vector3.ONE) -> CSGShape3D:
	node.operation = operation
	node.position = position
	node.rotation_degrees = rotation_deg
	node.scale = scale
	body.add_child(node)
	return node


func cylinder(radius: float, height: float, sides := 32) -> CSGCylinder3D:
	var c := CSGCylinder3D.new()
	c.radius = radius
	c.height = height
	c.sides = sides
	return c


func _initialize() -> void:
	body = CSGCombiner3D.new()
	get_root().add_child(body)

	# Head: a rounded puck over the tracked point, its top face carrying the thumbstick and buttons.
	var head := CSGSphere3D.new()
	head.radius = 0.036
	head.radial_segments = 40
	head.rings = 20
	part(head, Vector3(0, 0, -0.004), Vector3.ZERO, CSGShape3D.OPERATION_UNION, Vector3(1.0, 0.5, 1.08))

	# Grip: a short capsule raked back under the head.
	part(cylinder(0.019, 0.07), Vector3(0, -0.042, 0.016), Vector3(-15, 0, 0))
	var butt := CSGSphere3D.new()
	butt.radius = 0.019
	butt.radial_segments = 24
	butt.rings = 12
	part(butt, Vector3(0, -0.076, 0.025))

	# Thumbstick with a wide cap, and two face buttons ahead of it.
	part(cylinder(0.005, 0.01, 16), Vector3(0, 0.019, 0.006))
	part(cylinder(0.0105, 0.005, 24), Vector3(0, 0.025, 0.006))
	part(cylinder(0.0042, 0.004, 16), Vector3(-0.011, 0.017, -0.016))
	part(cylinder(0.0042, 0.004, 16), Vector3(0.011, 0.017, -0.016))

	# Trigger under the front of the head, where the index finger rests.
	var trigger := CSGBox3D.new()
	trigger.size = Vector3(0.016, 0.022, 0.01)
	part(trigger, Vector3(0, -0.019, -0.026), Vector3(30, 0, 0))


func _process(_delta: float) -> bool:
	frames += 1
	if frames < 3:
		return false
	var meshes: Array = body.get_meshes()
	if meshes.size() < 2:
		push_error("CSG produced no mesh")
		quit(1)
		return true
	write(meshes[0] as Transform3D, meshes[1] as ArrayMesh)
	quit(0)
	return true


func write(xf: Transform3D, mesh: ArrayMesh) -> void:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUT))
	var image := Image.create(4, 4, false, Image.FORMAT_RGB8)
	image.fill(Color8(52, 58, 66))
	image.save_png(OUT + "oxrsys_controller.png")
	var mtl := FileAccess.open(OUT + "oxrsys_controller.mtl", FileAccess.WRITE)
	mtl.store_string("newmtl body\nKd 1 1 1\nmap_Kd oxrsys_controller.png\n")
	var obj := FileAccess.open(OUT + "oxrsys_controller.obj", FileAccess.WRITE)
	obj.store_string("# OXRSys controller, generated by make_controller.gd from Godot CSG\nmtllib oxrsys_controller.mtl\nusemtl body\nvt 0.5 0.5\n")
	var base := 1
	var triangles := 0
	for s in mesh.get_surface_count():
		var arrays := mesh.surface_get_arrays(s)
		var vertices: PackedVector3Array = arrays[Mesh.ARRAY_VERTEX]
		var normals: PackedVector3Array = arrays[Mesh.ARRAY_NORMAL]
		var indices = arrays[Mesh.ARRAY_INDEX]
		for v in vertices:
			var p := xf * v
			obj.store_string("v %.6f %.6f %.6f\n" % [p.x, p.y, p.z])
		for n in normals:
			var q := (xf.basis * n).normalized()
			obj.store_string("vn %.6f %.6f %.6f\n" % [q.x, q.y, q.z])
		var count: int = indices.size() if indices != null else vertices.size()
		for i in range(0, count, 3):
			# Godot winds clockwise; OBJ is counter-clockwise.
			var a: int = (indices[i] if indices != null else i) + base
			var b: int = (indices[i + 2] if indices != null else i + 2) + base
			var c: int = (indices[i + 1] if indices != null else i + 1) + base
			obj.store_string("f %d/1/%d %d/1/%d %d/1/%d\n" % [a, a, b, b, c, c])
			triangles += 1
		base += vertices.size()
	print("oxrsys_controller: %d triangles" % triangles)
